dist: bionic
language: go

go:
  - 1.14.x

before_script: go mod download

script:
  - go build -v
  - go test ./...
  - go vet
  - find . -not \( \( -wholename './.git' -o -wholename '*/vendor/*' \) -prune \) -name '*.go' | xargs gofmt -s -d
