on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  publish-dockerhub:
    runs-on: [ self-hosted, public, linux, x64 ]
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bridgecrew/terraformer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildoptions: "--no-cache"
          tags: "latest"
